### ISSUE TITLE
Saving layouts in a workspace file

### ISSUE THREAD

**Issue by gtgthozz** [eamodio/vscode-restore-editors#12]
It would be nice to be able to open the same layout on another PC

**Comment by Yikes2000** [comment]
I second the suggestion.  Perhaps options for Export/Import layouts?

**Comment by seabye** [comment]
I also need! Now in order to do this, I am editing 'state.vscdb' manually to do this recovery.

**Comment by eamodio** [comment]
You can now import & export saved layouts to a `.json` file.

Closed by 01cc78f4443c0a03471f452e534a8d69463d45e7
