### ISSUE TITLE
request: save cursor positions

### ISSUE THREAD

**Issue by starlingjon** [eamodio/vscode-restore-editors#15]
i would like to use this extension to try to recover some of the window/tab workflow lost when migrating from vim, really the only thing in the way is that whenever i switch to a different layout i lose my place in all the editors. maybe this isn't possible but ideally when i recall a layout it should recall exactly where i was in each file in that layout so i can get back to work in that context without having to find where i was in each file

**Comment by eamodio** [comment]
I've added experimental support for this (sadly it's quite a hack as VS Code doesn't provide the information I need). For now, it's off by default and you can turn it on by setting `"restoreEditors.experimental.saveTabSelection": true` in yout settings.

Can you please try this out in tomorrow's (`v2023.11.24xx`) pre-release edition? Thank you so much!

You can switch to the pre-release edition, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

**Comment by starlingjon** [comment]
@eamodio thanks! this makes an already very useful extension even more useful. i did however find an issue, if you have the same file open more than once the line numbers for all of them will be the line number of the last editor for that file. from what i can gather it looks like the selection map is indexed by file, maybe there's another way to index it?

**Comment by eamodio** [comment]
Ah good catch. I'll find a better key -- thanks!

**Comment by eamodio** [comment]
Tomorrow's pre-release should better preserve that, but if you have the same file open in the same editor group it won't help. Still thinking of how I can handle that -- have some ideas.
