### ISSUE TITLE
No saved layouts found

### ISSUE THREAD

**Issue by LukeDickerson19** [eamodio/vscode-restore-editors#17]
Issue Q+A errored 404 for some reason so i created a feature request: upon installing this extension, restarting vs code, creating and saving a layout, restarting vs code, the layouts always say "No saved  layouts found". Please let me know if I'm doing anything wrong. This would be such an awesome extension.

VS Code Version: 1.84.0
OS: Manjaro 23.0.4

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

**Comment by LukeDickerson19** [comment]
I ended up just using the Project Manager extension. but basically the layouts should persist even after vs code is closed. i assume it saves them to a file, then reads from the file when vs code is reopened, i feel its probably something with my setup insteaed of the extension itself. no longer an issue though.

**Comment by eamodio** [comment]
The layouts definitely persist even if you close VS Code, but they are specific to the folder/workspace you open.

I'm going to close this then.
