### ISSUE TITLE
Opened editors aren't always properly saved

### ISSUE THREAD

**Issue by zabel-xyz** [eamodio/vscode-restore-editors#2]
This extension doesn't work with multiple columns.
- The cycle through the tabs seems to be done several times.
- Not all editors are restored (not always the last one)
(See my example below)

![editors](https://cloud.githubusercontent.com/assets/16486407/23585798/caefbee2-0187-11e7-9f95-304eca65b1a1.gif)

**Comment by eamodio** [comment]
@zabel-xyz can you try v0.0.4 and see if this is resolved for you?

**Comment by zabel-xyz** [comment]
I tried version 0.0.4, but the problem is still there ...
Sometimes some publishers are absent, sometimes some are duplicated...

**Comment by eamodio** [comment]
@zabel-xyz can you provide more details and maybe another screen grab? There is known limitations of this extension (because of the vscode api), that I can't restore any editors other than editors for real files. So that could explain why some are absent (but it should be consistently absent). And as for duplicated I would really love to see that.

Thanks!

**Comment by zabel-xyz** [comment]
Here some info...

I have two columns with 'real files'
Col1: extension.ts; plsqlDefinition.provider.ts; xyz_myFunc.sql;
Col2: package.json; README.md; CHANGELOG.md;

I save editors several times (of course with clear saved editors between each attempt)
I noticed that the result is different, if the active tabs aren't the same.
With the same active tabs, the result is often (not always) the same
Here some results (CTRL+D)

![image](https://cloud.githubusercontent.com/assets/16486407/23769306/39127b14-050f-11e7-9137-f3f034687134.png)
_1st tab of each colum active - Duplicated editor_

![image](https://cloud.githubusercontent.com/assets/16486407/23769425/a3e82e5c-050f-11e7-8d20-eed06ef2756a.png)
_Last tab of each column active - Missing editors_

![image](https://cloud.githubusercontent.com/assets/16486407/23769558/19ce46e2-0510-11e7-8b1b-3f92d68172a5.png)
_Last tab of each column active - Missing and duplicated editors_

Windows 10 / VSCode 1.10.1 / All others extensions disabled

**Comment by eamodio** [comment]
@zabel-xyz have you tried with 0.0.5 I posted last night? That *might* make a difference.

**Comment by zabel-xyz** [comment]
Yes, the results above are with this version

**Comment by eamodio** [comment]
@zabel-xyz ok thanks I will take a look -- though given the black magic nature of this stuff (because of the lack of a vscode api) I can't make any promises :)

**Comment by eamodio** [comment]
@zabel-xyz with any luck v0.1.0 will resolve the issue -- let me know

**Comment by zabel-xyz** [comment]
It works better, but sometimes some editors aren't saved.  (Especially when there are many)

![image](https://cloud.githubusercontent.com/assets/16486407/25302216/8493148a-2739-11e7-95d3-c359f1713a47.png)

Here README.md is not saved

**Comment by eamodio** [comment]
@zabel-xyz is the repo you are seeing this on publicly available?

**Comment by eamodio** [comment]
Resolved in 1.0
