### ISSUE TITLE
Editors can not be restored if I change the project directory name

### ISSUE THREAD

**Issue by sgon00** [eamodio/vscode-restore-editors#6]
Hi I am not sure why other people use this extension. VSCode can restore all previous opened editors on restart by default. The reason why I installed this extension is because I think the extension can save all opened editors to a file (db) inside the project's path, so that I can ignore the project directory name and path and move it to anywhere. Something like saving the session to `<path>/projectDir/.savedEditors`. But when I change the project directory name and path, this extension no longer works and I am unable to open saved editors anymore. I really don't know if this doesn't work, what is the point of this extension instead of using default vscode restore editors behavior? Thank you very much.

**Comment by eamodio** [comment]
In 1.0 a lot has changed, but the state is still stored within the VS Code workspace storage. Would an export/import feature work?
