### ISSUE TITLE
Alt+Right Arrow restores tabs

### ISSUE THREAD

**Issue by devpake** [eamodio/vscode-restore-editors#7]
Mac Catalina
vscode v1.42.1
vim 1.13.0

It seems that `alt + right arrow` recalls all the saved tabs back into the editor. This unfortunately conflicts with the standard ability to move the cursor by words using the same key combo.  Not sure if this is due to a conflict with the vim plugin.

**Comment by eamodio** [comment]
No longer applicable in 1.0
