### ISSUE TITLE
Jupyter Notebook Files

### ISSUE THREAD

**Issue by Sean-Ker** [eamodio/vscode-restore-editors#8]
Hi, 
Most of my work is centred around .ipynb (Jupyter Notebook) files which I work within vs-code.  The extension is not able to save this file type, most likely as they are web views. I do understand the limitations of vs-code and the difficulty of not providing an appropriate API for opened editors. Is there any way to handle this issue? Thank you. (:

**Comment by eamodio** [comment]
Resolved in 1.0
