### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by mcswell2001** [eamodio/vscode-restore-editors#9]
This is a question, not (yet) a request.  Apologies if this is the wrong place for questions; I couldn't find a better place...

I use VSC frequently on remote sites, and occasionally on my own computer.  When I log into a remote, I have to do a bunch of restores: split the view into three columns, open the files I used last time, and open a terminal.  As I say, I may do that for several different remotes.  VSC by itself certainly doesn't seem to support restoring such a setup, which I find bizarre--or if it does, it's certainly not well documented.  (My previous editor, jEdit, supported this very well.)

Is there a way to use your extension to do this?  I.e. save several configurations (meaning opened files, columns, etc.), and easily re-open them when I log into that remote.  If not--and I understand that may not be your use case--are you aware of any extension that does that?  I've spent more time than I should have searching for this...

**Comment by eamodio** [comment]
This should be resolved in 1.0
